some changes

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -34,8 +34,12 @@ jobs:
         run: |
           echo "${{ secrets.INSTANCE_PRIVATE_KEY }}" > private_key
           chmod 600 private_key
-          docker save nginx:dev | bzip2 | ssh -i private_key ${{ secrets.USERNAME }}@${{ secrets.IP }} 'bunzip2 | docker load'
-          ssh -i ${{ secrets.INSTANCE_PRIVATE_KEY }} ${{ secrets.USERNAME }}@${{ secrets.IP }} "docker image inspect nginx:dev > /dev/null 2>&1 && echo 'Image successfully loaded' || { echo 'Failed to load image'; exit 1; }"
+          
+          docker save nginx:dev | bzip2 | ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} 'bunzip2 | docker load'
+          
+          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} \
+          "docker image inspect nginx:dev > /dev/null 2>&1 && echo 'Image successfully loaded' || { echo 'Failed to load image'; exit 1; }"
+
 
   
   # deploy:
